estado_choices = (
    ('CREADO', 'CREADO'),
    ('PREPARANDO', 'PREPARANDO'),
    ('COMPLETADO', 'COMPLETADO'),
    ('ENVIADO', 'ENVIADO'),
    ('ENTREGADO', 'ENTREGADO'),
    ('DEVUELTO', 'DEVUELTO'),
    ('RECEPCIONADO', 'RECEPCIONADO'),
    ('PAGADO', 'PAGADO'),
    ('CANCELADO', 'CANCELADO'),
)
