# Generated by Django 5.0.6 on 2024-05-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0001_initial'),
        ('VENTAS', '0002_rename_order_pedidoitem_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productosPedido', to='STORE.producto'),
        ),
    ]
