# Generated by Django 5.0.6 on 2024-05-11 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('tipoDocumento', models.CharField(choices=[('dni', 'DNI'), ('nif', 'NIF'), ('cif', 'CIF'), ('pasaporte', 'Pasaporte'), ('nie', 'NIE')], max_length=20, null=True, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=60, verbose_name='Documento del Cliente')),
                ('password', models.CharField(max_length=50, unique=True, verbose_name='Contraseña del Cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('tipoCliente', models.CharField(blank=True, choices=[('particular', 'particular'), ('empresa', 'empresa')], max_length=200, verbose_name='Tipo de Cliente')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('comercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RRHH.empleado', verbose_name='Comercial Asignado')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDireccion', models.CharField(choices=[('contacto', 'Contacto'), ('envio', 'Envío'), ('facturacion', 'Facturación')], max_length=200, null=True, verbose_name='Tipo de Direccion')),
                ('tipoVia', models.CharField(blank=True, choices=[('calle', 'Calle'), ('avenida', 'Avenida'), ('camino', 'Camino'), ('via', 'Vía'), ('plaza', 'Plaza'), ('ronda', 'Ronda'), ('bulevar', 'Bulevar')], max_length=50, null=True, verbose_name='Tipo de via')),
                ('calle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero piso letra')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('codigoPostal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Codigo Postal')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='CRM.cliente')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'ordering': ['id'],
            },
        ),
    ]
