# Generated by Django 5.0.6 on 2024-05-11 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Pedido ID')),
                ('estado', models.CharField(choices=[('CREADO', 'CREADO'), ('PREPARANDO', 'PREPARANDO'), ('COMPLETADO', 'COMPLETADO'), ('ENVIADO', 'ENVIADO'), ('ENTREGADO', 'ENTREGADO'), ('DEVUELTO', 'DEVUELTO'), ('RECEPCIONADO', 'RECEPCIONADO'), ('PAGADO', 'PAGADO'), ('CANCELADO', 'CANCELADO')], max_length=50, verbose_name='Estado')),
                ('compra_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Compra total')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart', verbose_name='Carrito')),
            ],
        ),
    ]
